"""add transaction status

Revision ID: 1f2d920780e5
Revises: 886f10faf917
Create Date: 2025-11-15 22:59:17.525617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2d920780e5'
down_revision: Union[str, Sequence[str], None] = '886f10faf917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('transactions', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
