"""add_chat_messages_table

Revision ID: 597f62fc2949
Revises: d3c718475cf1
Create Date: 2025-11-19 16:31:15.053799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597f62fc2949'
down_revision: Union[str, Sequence[str], None] = 'd3c718475cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pin_hashed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pin_hashed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
